import Head from 'next/head';
import trpc from '../utils/tprc';

function Home() {
  const { data, isLoading } = trpc.useQuery(['hello', { text: 'client' }]);

  if (isLoading) {
    return <div>Loading...</div>;
  }
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <div>{JSON.stringify(data)}</div>
    </div>
  );
}

export default Home;
